package com.rayho.tsxiu.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.rayho.tsxiu.module_news.dao.Channel;
import com.rayho.tsxiu.module_news.dao.NewsCache;

import com.rayho.tsxiu.greendao.ChannelDao;
import com.rayho.tsxiu.greendao.NewsCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig channelDaoConfig;
    private final DaoConfig newsCacheDaoConfig;

    private final ChannelDao channelDao;
    private final NewsCacheDao newsCacheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        channelDaoConfig = daoConfigMap.get(ChannelDao.class).clone();
        channelDaoConfig.initIdentityScope(type);

        newsCacheDaoConfig = daoConfigMap.get(NewsCacheDao.class).clone();
        newsCacheDaoConfig.initIdentityScope(type);

        channelDao = new ChannelDao(channelDaoConfig, this);
        newsCacheDao = new NewsCacheDao(newsCacheDaoConfig, this);

        registerDao(Channel.class, channelDao);
        registerDao(NewsCache.class, newsCacheDao);
    }
    
    public void clear() {
        channelDaoConfig.clearIdentityScope();
        newsCacheDaoConfig.clearIdentityScope();
    }

    public ChannelDao getChannelDao() {
        return channelDao;
    }

    public NewsCacheDao getNewsCacheDao() {
        return newsCacheDao;
    }

}
