package com.rayho.tsxiu.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rayho.tsxiu.module_video.dao.VideoAutoPlay;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "VIDEO_AUTO_PLAY".
*/
public class VideoAutoPlayDao extends AbstractDao<VideoAutoPlay, Long> {

    public static final String TABLENAME = "VIDEO_AUTO_PLAY";

    /**
     * Properties of entity VideoAutoPlay.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Vid = new Property(1, String.class, "vid", false, "VID");
        public final static Property Autoplay = new Property(2, boolean.class, "autoplay", false, "AUTOPLAY");
    }


    public VideoAutoPlayDao(DaoConfig config) {
        super(config);
    }
    
    public VideoAutoPlayDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VIDEO_AUTO_PLAY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"VID\" TEXT NOT NULL UNIQUE ," + // 1: vid
                "\"AUTOPLAY\" INTEGER NOT NULL UNIQUE );"); // 2: autoplay
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VIDEO_AUTO_PLAY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, VideoAutoPlay entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getVid());
        stmt.bindLong(3, entity.getAutoplay() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, VideoAutoPlay entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getVid());
        stmt.bindLong(3, entity.getAutoplay() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public VideoAutoPlay readEntity(Cursor cursor, int offset) {
        VideoAutoPlay entity = new VideoAutoPlay( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // vid
            cursor.getShort(offset + 2) != 0 // autoplay
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, VideoAutoPlay entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setVid(cursor.getString(offset + 1));
        entity.setAutoplay(cursor.getShort(offset + 2) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(VideoAutoPlay entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(VideoAutoPlay entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(VideoAutoPlay entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
